title: "Sanjan's Internship Log"
description: Weekly log, projects, and insights from my SynerSense internship.
theme: jekyll-theme-hacker
show_downloads: false
google_analytics: UA-XXXXXXXXX-X  # optional
