title: "Internship Docs"
description: Weekly log, projects, and insights from my SynerSense internship.
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

baseurl: "/Internship-log"
url: "https://sanjanb.github.io/Internship-log"

# Just the Docs settings
just_the_docs:
  navigation: _data/navigation.yml            
  enable_copy_code_button: true
  logo: /assets/images/logo.png
  favicon_ico: /assets/images/favicon.ico
  color_scheme: "dark"
  heading_anchors: true
  search_enabled: true
  show_last_edit_time: true
  nav_sort: case_insensitive
  mermaid:
    version: "9.4.3"
  aux_links:
    View on GitHub: https://github.com/sanjanb/internship-log
  scripts:
    - /assets/js/back-to-top.js

sass:
  load_paths:
    - _sass
    - assets/css
