title: "Sanjan's Internship Docs"
description: Weekly log, projects, and insights from my SynerSense internship.
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

baseurl: "/Internship-log"
url: "https://sanjanb.github.io/Internship-log"  # Make sure this matches your GitHub Pages URL

sass:
  load_paths:
    - _sass
    - assets/css

just_the_docs:
  logo: /assets/images/logo.png
  favicon_ico: /assets/images/favicon.ico
  color_scheme: "dark"

  heading_anchors: true
  search_enabled: true
  enable_copy_code_button: true
  show_last_edit_time: true
  nav_sort: case_insensitive

  navigation: true  # Enables _data/navigation.yml sidebar
  collections:
    logs:
      output: true
      permalink: /logs/:path/

  aux_links:
    View on GitHub: https://github.com/sanjanb/internship-log

  scripts:
    - /assets/js/back-to-top.js

  mermaid:
    version: "9.4.3"
