title: "Sanjan's Internship Log"
description: "Weekly logs, tasks, and learnings from SynerSense internship."
remote_theme: just-the-docs/just-the-docs  # or mmistakes/minimal-mistakes
color_scheme: light
