title: "Sanjan's Internship Docs"
description: Weekly log, projects, and insights from my SynerSense internship.
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
baseurl: "/Internship-log"


# Enable sidebar nav
just_the_docs:
  logo: /assets/images/logo.png
  favicon_ico: /assets/images/favicon.ico  # optional
  color_scheme: "dark"
  search_enabled: true
  show_last_edit_time: true
  nav_sort: case_insensitive
  collections:
    logs:
      permalink: "/:path/"
      output: true
  aux_links:
    View on GitHub: https://github.com/sanjanb/internship-log
  scripts:
    - /assets/js/back-to-top.js

sass:
  load_paths:
    - _sass
    - assets/css

url: "https://sanjanb.github.io/Internship-log"  # change this to your actual repo
