title: "Sanjan's Internship Log"
description: Weekly log, projects, and insights from my SynerSense internship.
remote_theme: just-the-docs/minimal-mistakes
show_downloads: false
google_analytics: UA-XXXXXXXXX-X  # optional
